### ISSUE TITLE
Missing .ci_support files after rerender

### ISSUE THREAD

**Issue by twrightsman** [conda-forge/ledger-feedstock#11]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

@conda-forge/core I haven't attempted to build this feedstock locally since conda-forge used CircleCI. I see under the [documentation](https://conda-forge.org/docs/maintainer/updating_pkgs.html#testing-changes-locally) that I should now be running `python build-locally.py` but I have no YAML files under `.ci_support`, even after rerendering. What steps can I take to get a local build running the modern way?

**Comment by beckermr** [comment]
This feedstock is only building python 2.7: https://github.com/conda-forge/ledger-feedstock/blob/master/recipe/meta.yaml#L17

You'll need to fix that by changing the selector.

**Comment by twrightsman** [comment]
Thank you for your help @beckermr!
