### ISSUE TITLE
Replacement maintainer requested

### ISSUE THREAD

**Issue by twrightsman** [conda-forge/ledger-feedstock#28]
### Comment:

I no longer have the time/interest to maintain this feedstock; can @conda-forge/core consider archiving this unless a new maintainer steps up?

**Comment by ThatIsAPseudo** [comment]
@twrightsman I may be interested in maintaining this; though I have little knowledge of conda (but I guess it's still better than archiving it)

**Comment by twrightsman** [comment]
@ThatIsAPseudo Awesome! The `conda-forge` [maintainer documentation](https://conda-forge.org/docs/maintainer/00_intro.html) may be a good place to start learning. Let me know if you have questions.

The two main things you'd do as maintainer are:
1) Merge version bump PRs (_e.g._ https://github.com/conda-forge/ledger-feedstock/pull/26)
2) Merge rerender PRs (_e.g._ https://github.com/conda-forge/ledger-feedstock/pull/27 for an auto-generated one)
    - You can also rerender manually in a fork (e.g. https://github.com/conda-forge/ledger-feedstock/pull/29)

**Comment by jaimergp** [comment]
You can use this to request membership safely: https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-add-user-username

Feel free to ask us (the community) any question at [`#conda-forge:matrix.org`](https://app.element.io/#/room/#conda-forge:matrix.org)

**Comment by twrightsman** [comment]
Since @ThatIsAPseudo has graciously offered to try to maintain this package I will close this! Thanks everyone
